//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace casusB2D3_BU
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class casusB2D3_DBContainer : DbContext
    {
        public casusB2D3_DBContainer()
            : base("name=casusB2D3_DBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountRole> AccountRoleSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Contact> ContactSet { get; set; }
        public virtual DbSet<ProductReview> ProductReviewSet { get; set; }
        public virtual DbSet<Product> ProductSet { get; set; }
        public virtual DbSet<Category> CategorySet { get; set; }
        public virtual DbSet<Supplier> SupplierSet { get; set; }
        public virtual DbSet<OperationArea> OperationAreaSet { get; set; }
        public virtual DbSet<History> HistorySet { get; set; }
        public virtual DbSet<Occasion> OccasionSet { get; set; }
        public virtual DbSet<News> NewsSet { get; set; }
    }
}
