//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace casusB2D3_BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public int Version { get; set; }
        public System.DateTime LogDate { get; set; }
        public bool IsDeleted { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
        public virtual Occasion Occasion { get; set; }
        public virtual News News { get; set; }
    }
}
