//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace casusB2D3_BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReview
    {
        public int Id { get; set; }
        public string ReviewText { get; set; }
        public Nullable<int> StarRating { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public bool Anonymous { get; set; }
        public Nullable<int> UserId { get; set; }
        public int ProductId { get; set; }
        public int ProductVersion { get; set; }
    
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
    }
}
