//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace casusB2D3_BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductReview = new HashSet<ProductReview>();
        }
    
        public int Id { get; set; }
        public int Version { get; set; }
        public string Name { get; set; }
        public string Information { get; set; }
        public System.DateTime ExirationDate { get; set; }
        public int TimesViewed { get; set; }
        public bool Compensation { get; set; }
        public int Price { get; set; }
        public bool IsApproved { get; set; }
        public int CategoryId { get; set; }
        public int SupplierId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReview> ProductReview { get; set; }
        public virtual Category Category { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual History History { get; set; }
    }
}
